version: "3.8"
services:
  backend:
    build: ./server/index.js
    environment:
      - PORT=5000
      - SITE_URL=https://www.bestapbuilder.com
    expose:
      - 5000

  nginx:
    image: nginx:stable
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  # certbot or other ACME client should be configured to obtain TLS certs for the domain
  # This compose file is a starting point; follow Let's Encrypt instructions to obtain certs
